Add missing param to success
Addresses Swift compilation error:
```
Swish/Source/Protocols/Request.swift:29:21: Missing argument for parameter #1 in call
```